image: Visual Studio 2017
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: build.bat
test: off
version: 1.1.0.{build}
artifacts:
  - path: TickSpec\bin\Release
    name: release
  - path: 'packed_nugets\*.nupkg'
    type: NuGetPackage
nuget:
  account_feed: false
  project_feed: false